### PR TITLE
Make autoroles config command

### PR DESCRIPTION
**Pull request by notsniped**
### `/autoroles` command
will let a server admin to set a role to provide all new members with.

### CODE REVIEW

**Comment by notsniped** [comment]
Wai it also updated the paths

**Comment by notsniped** [comment]
Paths have to be merged out of necessity

**Comment by notsniped** [comment]
Ready to merge, just waiting for approval by @archisha69

**Comment by notsniped** [comment]
Ok not yet ready for merge

**Comment by notsniped** [comment]
Now ready to mergent

**Comment by XyrenTheCoder** [comment]
> Ready to merge, just waiting for approval by @archisha69 

why me to approve it its ur bot

**Comment by XyrenTheCoder** [comment]
> Ready to merge, just waiting for approval by @archisha69 

just merge it first we can debug later

**Comment by notsniped** [comment]
If something goes wrong I will have to make another commit on this (am i lazy?)

**Comment by notsniped** [comment]
Ok i am lazy

**Comment by notsniped** [comment]
Whatever, this codebase is outdated anyway. I'll just merge it and continue on lazer.

**Pull request merged**
